#pragma once

#define BGM_EYE_CREEPY 0x11B
#define BGM_EYE_GIRL 0x11C
#define BGM_EYE_BOY 0x11D

#define BGM_VICTORY_TRAINER_BATTLE 0x136
#define BGM_VICTORY_SPECIAL 0x138

#define BGM_BATTLE_RSE_GYM_LEADER 0x109
#define BGM_BATTLE_RSE_TRAINER 0x10A
#define BGM_CYCLING 0x11A
#define BGM_BATTLE_GYM_LEADER 0x128
#define BGM_BATTLE_TRAINER 0x129
#define BGM_BATTLE_WILD 0x12A
#define BGM_BATTLE_CHAMPION 0x12B
#define BGM_SURFS_UP 0x131
#define BGM_BATTLE_DEOXYS 0x153
#define BGM_BATTLE_LEGENDARY_BIRDS 0x154
#define BGM_BATTLE_MEWTWO 0x155

#define BGM_VICTORY_WILD_POKE 0x137
#define BGM_VICTORY_GYM 0x138

#define BGM_RANDOM_BATTLE_MUSIC 0xFEFE

#define MUS_DUMMY 0
#define SE_STOP 0
#define SE_USE_ITEM 1
#define SE_PC_LOGON 2
#define SE_PC_OFF 3
#define SE_PC_ON 4
#define SE_SELECT 5
#define SE_WIN_OPEN 6
#define SE_WALL_HIT 7
#define SE_DOOR_OPEN 8
#define SE_EXIT_ROOM 9
#define SE_HOP 0xA
#define SE_BIKE_BELL 0xB
#define SE_NOT_VERY_EFFECTIVE 0xC
#define SE_EFFECTIVE 0xD
#define SE_SUPER_EFFECTIVE 0xE
#define SE_POKE_BALL_OPEN 0xF
#define SE_POKE_BALL_CLOSE 0x10
#define SE_FLEE 0x11
#define SE_SLIDING_DOOR_OPEN 0x12
#define SE_BREAK_DOOR_OPEN 0x14
#define SE_EXCLAIM 0x15
#define SE_FALSE 0x16
#define SE_POKE_BALL_SHAKE 0x17
#define SE_CASINO_STOP_SLOT_REEL 0x18
#define SE_CORRECT 0x19
#define SE_ERROR 0x1A
#define SE_EXP 0x1B
#define SE_HOP_ON_BIKE 0x1C
#define SE_LOCK 0x1D
#define SE_UNLOCK 0x1E
#define SE_LAVARIDGE_GYM_DIG 0x21
#define SE_ICE_BREAK 0x23
#define SE_ICE_CRACK 0x24
#define SE_FALL 0x25
#define SE_DOOR_SHUT 0x26
#define SE_WARP_AWAY 0x27
#define SE_WARP_IN 0x28
#define SE_SLIDE 0x29
#define SE_TURN_SWITCH_FLIP 0x2A
#define SE_POKE_BALL_BOUNCE_1 0x32
#define SE_POKE_BALL_BOUNCE_2 0x32
#define SE_POKE_BALL_BOUNCE_3 0x33
#define SE_POKE_BALL_BOUNCE_4 0x34
#define SE_POKE_BALL_TRADE 0x35
#define SE_THROW_POKE_BALL 0x36
#define SE_NOTE_C 0x37
#define SE_NOTE_D 0x38
#define SE_NOTE_E 0x39
#define SE_NOTE_F 0x3A
#define SE_NOTE_G 0x3B
#define SE_NOTE_A 0x3C
#define SE_NOTE_B 0x3D
#define SE_NOTE_C1 0x3E
#define SE_PUDDLE 0x3F
#define SE_BOARDWALK 0x40
#define SE_SLOTS_CREDITS 0x41
#define SE_DING_DONG 0x42
#define SE_RED_BALLOON 0x43
#define SE_BLUE_BALLOON 0x44
#define SE_YELLOW_BALLOON 0x45
#define SE_BREAKABLE_DOOR 0x46
#define SE_MUD_BALL 0x47
#define SE_BT_START 0x61
#define SE_POKENAV_ONE_BEEP 0x65
#define SE_POKENAV_TWO_BEEPS 0x66
#define SE_POKENAV_ON 0x67
#define SE_POKENAV_OFF 0x68
#define SE_POKENAV_SEARCHING 0x69
#define SE_FLUTE 0x6E
#define SE_CUT 0x79
#define SE_ROCK_SMASH 0x7C
#define SE_CHOMP 0x9A
#define SE_MUD_SLAP 0xA1
#define SE_LEAVES 0xA2
#define SE_GLASS_BREAK 0xBF
#define SE_EARTHQUAKE 0xE3

#define SE_RG_W_DOOR 241        // Door
#define SE_RG_CARD1 242         // Trainer Card 1
#define SE_RG_CARD2 243         // Trainer Card 2
#define SE_RG_CARD3 244         // Trainer Card 3
#define SE_RG_BAG1 245          // Bag Scroll
#define SE_RG_BAG2 246          // Bag Pocket Change
#define SE_RG_GETTING 247
#define SE_MONEY 248
#define SE_SHIP_HORN 249
#define SE_SAND_FOOTSTEP 250
#define SE_GRASS_FOOTSTEP 251
#define SE_RG_HELP_MENU_ERROR 252
#define SE_RG_DEOXYS_MOVE 253
#define SE_RG_EXCELLENT 254

#define SE_CAUGHT_POKEMON 0x13F
#define MUS_FANFA1 0x101
#define MUS_FANFA2 0x10D

#define MUS_MOVE_DELETED          270 // MUS_ME_WASURE
#define MUS_TOO_BAD               271 // MUS_ME_ZANNEN
// New FRLG Music
#define MUS_FOLLOW_ME             272 // MUS_RG_ANNAI
#define MUS_GAME_CORNER           273 // MUS_RG_SLOT
#define MUS_ROCKET_HIDEOUT        274 // MUS_RG_AJITO
#define MUS_GYM                   275 // MUS_RG_GYM
#define MUS_JIGGLYPUFF            276 // MUS_RG_PURIN
#define MUS_INTRO_FIGHT           277 // MUS_RG_DEMO
#define MUS_TITLE                 278 // MUS_RG_TITLE
#define MUS_CINNABAR              279 // MUS_RG_GUREN
#define MUS_LAVENDER              280 // MUS_RG_SHION
#define MUS_HEAL_UNUSED           281 // MUS_RG_KAIHUKU
#define MUS_CYCLING               282 // MUS_RG_CYCLING
#define MUS_ENCOUNTER_ROCKET      283 // MUS_RG_ROCKET
#define MUS_ENCOUNTER_GIRL        284 // MUS_RG_SHOUJO
#define MUS_ENCOUNTER_BOY         285 // MUS_RG_SHOUNEN
#define MUS_HALL_OF_FAME          286 // MUS_RG_DENDOU
#define MUS_VIRIDIAN_FOREST       287 // MUS_RG_T_MORI
#define MUS_MT_MOON               288 // MUS_RG_OTSUKIMI
#define MUS_POKE_MANSION          289 // MUS_RG_POKEYASHI
#define MUS_CREDITS               290 // MUS_RG_ENDING
#define MUS_ROUTE1                291 // MUS_RG_LOAD01
#define MUS_ROUTE24               292 // MUS_RG_OPENING
#define MUS_ROUTE3                293 // MUS_RG_LOAD02
#define MUS_ROUTE11               294 // MUS_RG_LOAD03
#define MUS_VICTORY_ROAD          295 // MUS_RG_CHAMP_R
#define MUS_VS_GYM_LEADER         296 // MUS_RG_VS_GYM
#define MUS_VS_TRAINER            297 // MUS_RG_VS_TORE
#define MUS_VS_WILD               298 // MUS_RG_VS_YASEI
#define MUS_VS_CHAMPION           299 // MUS_RG_VS_LAST
#define MUS_PALLET                300 // MUS_RG_MASARA
#define MUS_OAK_LAB               301 // MUS_RG_KENKYU
#define MUS_OAK                   302 // MUS_RG_OHKIDO
#define MUS_POKE_CENTER           303 // MUS_RG_POKECEN
#define MUS_SS_ANNE               304 // MUS_RG_SANTOAN
#define MUS_SURF                  305 // MUS_RG_NAMINORI
#define MUS_POKE_TOWER            306 // MUS_RG_P_TOWER
#define MUS_SILPH                 307 // MUS_RG_SHIRUHU
#define MUS_FUCHSIA               308 // MUS_RG_HANADA
#define MUS_CELADON               309 // MUS_RG_TAMAMUSI
#define MUS_VICTORY_TRAINER       310 // MUS_RG_WIN_TRE
#define MUS_VICTORY_WILD          311 // MUS_RG_WIN_YASEI
#define MUS_VICTORY_GYM_LEADER    312 // MUS_RG_WIN_GYM
#define MUS_VERMILLION            313 // MUS_RG_KUCHIBA
#define MUS_PEWTER                314 // MUS_RG_NIBI
#define MUS_ENCOUNTER_RIVAL       315 // MUS_RG_RIVAL1
#define MUS_RIVAL_EXIT            316 // MUS_RG_RIVAL2
#define MUS_DEX_RATING            317 // MUS_RG_FAN2
#define MUS_OBTAIN_KEY_ITEM       318 // MUS_RG_FAN5
#define MUS_CAUGHT_INTRO          319 // MUS_RG_FAN6
#define MUS_PHOTO                 320 // MUS_ME_RG_PHOTO
#define MUS_GAME_FREAK            321 // MUS_RG_TITLEROG
#define MUS_CAUGHT                322 // MUS_RG_GET_YASEI
#define MUS_NEW_GAME_INSTRUCT     323 // MUS_RG_SOUSA
#define MUS_NEW_GAME_INTRO        324 // MUS_RG_SEKAIKAN
#define MUS_NEW_GAME_EXIT         325 // MUS_RG_SEIBETU
#define MUS_POKE_JUMP             326 // MUS_RG_JUMP
#define MUS_UNION_ROOM            327 // MUS_RG_UNION
#define MUS_NET_CENTER            328 // MUS_RG_NETWORK
#define MUS_MYSTERY_GIFT          329 // MUS_RG_OKURIMONO
#define MUS_BERRY_PICK            330 // MUS_RG_KINOMIKUI
#define MUS_SEVII_CAVE            331 // MUS_RG_NANADUNGEON
#define MUS_TEACHY_TV_SHOW        332 // MUS_RG_OSHIE_TV
#define MUS_SEVII_ROUTE           333 // MUS_RG_NANASHIMA
#define MUS_SEVII_DUNGEON         334 // MUS_RG_NANAISEKI
#define MUS_SEVII_123             335 // MUS_RG_NANA123
#define MUS_SEVII_45              336 // MUS_RG_NANA45
#define MUS_SEVII_67              337 // MUS_RG_NANA67
#define MUS_POKE_FLUTE            338 // MUS_RG_POKEFUE
#define MUS_VS_DEOXYS             339 // MUS_RG_VS_DEO
#define MUS_VS_MEWTWO             340 // MUS_RG_VS_MYU2
#define MUS_VS_LEGEND             341 // MUS_RG_VS_DEN
#define MUS_ENCOUNTER_GYM_LEADER  342 // MUS_RG_EXEYE
#define MUS_ENCOUNTER_DEOXYS      343 // MUS_RG_DEOEYE
#define MUS_TRAINER_TOWER         344 // MUS_RG_T_TOWER
#define MUS_SLOW_PALLET           345 // MUS_RG_SLOWMASARA
#define MUS_TEACHY_TV_MENU        346 // MUS_RG_TVNOIZE

//Squeetz Music Patch
#define MUS_DD_MAPSCREEN		  	0x15B
#define MUS_DD_SKULLKER_HIDEOUT		0x15C
#define MUS_DD_ART_MUSEUM			0x15D
#define MUS_DD_AREA_CLEAR			0x15E
#define MUS_DD_AREA_1_INTRO			0x15F
#define MUS_DD_FILE_SELECT			0x160
#define MUS_DD_TREASURE				0x161
#define MUS_DD_3RD_GEAR				0x162
#define MUS_DD_SUNKEN_KURU			0x163
#define MUS_DD_INTRO_AREA			0x164
#define MUS_DD_KURU_RUINS			0x165
#define MUS_DD_METAL_CITY			0x166
#define MUS_DD_SKULLKER_DRILL		0x167
#define MUS_DD_JILL_VS_CROOG		0x168
#define MUS_DD_DRLL_DOZER_RETURNS	0x169
#define MUS_DD_CROOG_DOOM_DOZER		0x16A
#define MUS_DD_GEARMO_SAVE			0x16B
#define MUS_DD_MIDBOSS_BATTLE_3		0x16C
#define MUS_DD_CARRIE_THEME			0x16D
#define MUS_DD_CORRUPT_COMMISSIONER	0x16E
#define MUS_DD_PROFESSOR_THEME		0x16F
#define MUS_DD_MIDBOSS_BATTLE_2		0x170
#define MUS_DD_TO_THE_DOOM_DOZER	0x171
#define MUS_DD_WELCOME_TO_THE_CLINK	0x172
#define MUS_DD_REDIRECTING_THE_MISSILE	0x173
#define MUS_DD_DOOM_DOZER_REVEALED		0x174
#define MUS_DD_REMAINING_DIAMONDS	0x175
#define MUS_DD_CARRIE_PLEA			0x176
#define MUS_DD_BOSS_BATTLE 			0x177
#define MUS_DD_ITEM_BOUGHT			0x178
#define MUS_RSE_LITTLE_BOY_ENCOUNTER	0x179
#define MUS_RSE_MALE_ENCOUNTER		0x17A
#define MUS_RSE_SWIMMER_ENCOUNTER	0x17B
#define MUS_RSE_METEOR_FALLS		0x17C
#define MUS_RSE_GLOWING_ORB			0x17D
#define MUS_RSE_SAILOR_ENCOUNTER	0x17E
#define MUS_RSE_FEMALE_ENCOUNTER	0x17F
#define MUS_RSE_DESERT				0x180
#define MUS_RSE_EXPERT_ENCOUNTER	0x181
#define MUS_RSE_ACE_ENCOUNTER		0x182
#define MUS_RSE_ASHLANDS			0x183
#define MUS_RSE_WEIRDO_ENCOUNTER	0x184
#define MUS_RSE_MOUNT_PYRE_OUTER	0x185
#define MUS_RSE_REGI_CHAMBER		0x186
#define MUS_RSE_HEAVY_RAINFALL		0x187
#define MUS_RSE_LITTLE_GIRL_ENCOUNTER	0x188
#define MUS_RSE_ELITE_4_ENCOUNTER	0x189
#define MUS_RSE_FATTY_ENCOUNTER		0x18A
#define MUS_RSE_PYRAMID				0x18B
#define MUS_RSE_PYRAMID_TOP			0x18C
#define MUS_RSE_BATTLE_DOME			0x18D
#define MUS_RSE_FRONTIER_BRAIN_BATTLE	0x18E
#define MUS_RSE_CHAMPION_BATTLE		0x18F
#define MUS_RSE_REGI_BATTLE			0x190
#define MUS_RSE_LEGEND_BATTLE		0x191
#define MUS_HAMTARO_HAM_HAM_HEARTBREAK	0x192
#define MUS_SN_PEACEFUL_TIME		0x193
#define MUS_SN_IN_THE_END_OF_THE_SADNESS	0x194
#define MUS_SN_UNCONTROLLABLE_RAGE	0x195
#define MUS_SN_HURRY_UP				0x196
#define MUS_SN_VICIOUS_PLOT			0x197
#define MUS_SN_THE_MEETING			0x198
#define MUS_SN_TO_TOMORROW			0x199
#define MUS_RSE_RIVAL_BATTLE		0x19A
#define MUS_RSE_FALLARBOR_TOWN		0x19B
#define MUS_RSE_GRUNT_BATTLE		0x19C
#define MUS_RSE_ELITE_4_BATTLE		0x19D
#define MUS_RSE_EVIL_LEADER_BATTLE	0x19E
#define MUS_RSE_WILD_BATTLE			0x19F
#define MUS_SQUEETZ_BATTLE_THEME	0x1A0
#define MUS_RSE_UNUSED_THEME_1		0x1A1
#define MUS_RSE_INTRO_THEME			0x1A2
#define MUS_RSE_ABANDONED_SHIP		0x1A3
#define MUS_RSE_VERDANTURF_TOWN		0x1A4
#define MUS_RSE_ROUTE_THEME_1		0x1A5
#define MUS_RSE_ROUTE_THEME_2 		0x1A6
#define MUS_RSE_MAY_THEME			0x1A7
#define MUS_RSE_SUBMARINE_HEIST		0x1A8
#define MUS_RSE_DEWFORD_TOWN		0x1A9
#define MUS_RSE_SOOTOPOLIS_CITY		0x1AA
#define MUS_RSE_CHAMPION_ENCOUNTER	0x1AB
#define MUS_RSE_THE_END				0x1AC
#define MUS_RSE_BATTLE_FACTORY		0x1AD
#define MUS_RSE_MART 				0x1AE
#define MUS_RSE_LILYCOVE_CITY		0x1AF
#define MUS_RSE_GAME_CORNER			0x1B0
#define MUS_RSE_TRICK_HOUSE			0x1B1
#define MUS_RSE_CONTEST_LOBBY		0x1B2
#define MUS_RSE_BATTLE_FRONTIER		0x1B3
#define MUS_RSE_BATTLE_ARENA		0x1B4
#define MUS_RSE_BATTLE_FRONTIER_FANFARE_1	0x1B5
#define MUS_RSE_POKENAV_REIGSTRY	0x1B6
#define MUS_RSE_BATTLE_PALACE		0x1B7
#define MUS_RSE_BATTLE_TOWER		0x1B8
#define MUS_RSE_BATTLE_FRONTIER_FANFARE_2	0x1B9
#define MUS_RSE_BATTLE_PIKE			0x1BA
#define MUS_RSE_UNUSED_ROUTE_38		0x1BB
#define MUS_RSE_INTERVIEWER_ENCOUNTER	0x1BC
#define MUS_RSE_LITTLEROOT_TOWN_ALT		0x1BD
#define MUS_RSE_ELITE_4_VICTORY		0x1BE
#define MUS_RSE_UNUSED_THEME_2		0x1BF
#define MUS_RSE_ROUTE_THEME_3		0x1C0
#define MUS_RSE_ROUTE_THEME_4		0x1C1
#define MUS_RSE_ROUTE_THEME_5		0x1C2
#define MUS_RSE_PETALBURG_CITY		0x1C3
#define MUS_RSE_OLDALE_TOWN			0x1C4
#define MUS_RSE_SURF				0x1C5
#define MUS_RSE_PETALURG_WOODS		0x1C6
#define MUS_RSE_ART_MUSEUM			0x1C7
#define MUS_RSE_OCEANIC_MUSEUM		0x1C8
#define MUS_RSE_FORTREE_CITY		0x1C9
#define MUS_RSE_PROFESSOR_LAB		0x1CA
#define MUS_RSE_BATTLE_TOWER_RUBY	0x1CB
#define MUS_RSE_SPIN_THE_WHEEL		0x1CC
#define MUS_RSE_MAUVILLE_CITY		0x1CD
#define MUS_RSE_POKECENTER			0x1CE
#define MUS_RSE_BICYCLE_RIDE		0x1CF
#define MUS_RSE_LITTLEROOT_TOWN 	0x1D0
#define MUS_RSE_MOUNT_CHIMNEY		0x1D1
#define MUS_RSE_HELP_BIRCH			0x1D2
#define MUS_RSE_DIVING_THEME		0x1D3
#define MUS_RSE_FOLLOW_ME			0x1D4
#define MUS_RSE_BRENDAN_THEME		0x1D5
#define MUS_RSE_EVIL_TEAM_DEFEATED	0x1D6
#define MUS_RSE_UP_THE_GONDOLA		0x1D7
#define MUS_RSE_SAFARI_ZONE			0x1D8
#define MUS_RSE_VICTORY_ROAD		0x1D9
#define MUS_RSE_GLORY_ROOM			0x1DA
#define MUS_RSE_EVIL_TEAM_BASE		0x1DB
#define MUS_RSE_BOAT_RIDE			0x1DC
#define MUS_RSE_MOUNT_PYRE 			0x1DD
#define MUS_RSE_HALL_OF_FAME		0x1DE
#define MUS_RSE_CONTEST_THEME		0x1DF
#define MUS_RSE_EVIL_TEAM_APPEARS	0x1E0
#define MUS_RSE_CONTEST_CHAMPIONSHIP	0x1E1
#define MUS_RSE_RESULT_ANNOUNCEMENT	0x1E2
#define MUS_RSE_SLATEPORT_CITY		0x1E3
#define MUS_RSE_DROUGHT				0x1E4
#define MUS_RSE_THE_END_2			0x1E5
#define MUS_RSE_INTRO_1				0x1E6
#define MUS_RSE_INTRO_2				0x1E7
#define MUS_RSE_TITLESCREEN			0x1E8
#define MUS_DD_RED_DOZER			0x1E9
#define MUS_DD_GEAR_OBTAINED		0x1EA
#define MUS_DD_MIDBOSS_BATTLE_1		0x1EB
#define MUS_DD_KURU_RUINS_TRAP_ROOM	0x1EC
#define MUS_DD_SCREW_BREAKER		0x1ED
#define MUS_DD_WRONG_TRAILER_PICKUP	0x1EE
#define MUS_DD_ENGAGE_DRILL_DOZER	0x1EF
#define MUS_DD_AREA_2_INTRO			0x1F0
#define MUS_DD_CROOG_THEME			0x1F1
#define MUS_DD_AREA_3_INTRO			0x1F2
#define MUS_DD_AREA_4_INTRO			0x1F3
#define MUS_DD_GAME_OVER			0x1F4
#define MUS_DD_YOUR_RANK_IS			0x1F5
#define MUS_DD_YOUR_RANK_IS_PICKPOCKET	0x1F6
#define MUS_DD_YOUR_RANK_IS_BOSS	0x1F7
#define MUS_DD_YOUR_RANK_IS_CRIME_BOSS	0x1F8
#define MUS_EMPTY_1					0x1F9
#define MUS_EMPTY_2					0x1FA
#define MUS_EMPTY_3					0x1FB
#define MUS_EMPTY_4					0x1FC
#define MUS_EMPTY_5					0x1FD
#define MUS_EMPTY_6					0x1FE
#define MUS_EMPTY_7					0x1FF
